### ISSUE TITLE
Filebeat issue!

### ISSUE THREAD

**Issue by ShanwHa** [Qumulo/auditlogs-elasticsearch#1]
Hello. 

I just set up my elastic search w/ qumulo syslog but there are no "Docs count". 

Please check my attaches and guide me. 

1. I was use config files by default which you had uploaded.
2. I just edited the node name to "u1" which has rsyslog & docker leader node.

![log](https://user-images.githubusercontent.com/68646594/88176290-ff93ed00-cc61-11ea-8760-de9a2a05944d.JPG)
![docker staus](https://user-images.githubusercontent.com/68646594/88176054-b479da00-cc61-11ea-9e23-8d9544b9fa39.JPG)
![docker2](https://user-images.githubusercontent.com/68646594/88176062-b6439d80-cc61-11ea-9e37-aff11de79b59.JPG)

**Comment by TommyUnger** [comment]
We will continue to help investigate this issue in Slack.

**Comment by TommyUnger** [comment]
Hopefully you were able to figure this out with Mike Kade. If not, please continue to use Slack to work on this issue.
